FROM ubuntu:18.04
# a few minor docker-specific tweaks
# see https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap
RUN mkdir /yang

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["/bin/bash"]